schedules:
- cron: "0 0 * * *"
  displayName: Daily GC
  always: true

stages:
  - stage: gc_stage
    dependsOn: []
    jobs:
    - job: gc_job
      timeoutInMinutes: 30
      steps:
        - bash: |
            go env
            ls $PATH
            ls $HOME
            export AZURE_SUBSCRIPTION_ID=$(az.subscription_id)
            export AZURE_TENANT_ID=$(az.tenant_id)
            export AZURE_CLIENT_ID=$(sp.client_id)
            export AZURE_CLIENT_SECRET=$(sp.client_secret)

            .pipelines/scripts/daily-gc.sh
          displayName: gc aks and resource groups
