trigger: none

pool:
  vmImage: ubuntu-18.04

variables:
  DisableDockerDetector: true
  # IMAGE_REGISTRY: $(registry.url)

stages:
  - stage: ccm_image_stage
    dependsOn: []
    jobs:
    - job: build_push_ccm_image_job
      timeoutInMinutes: 30
      steps:
        - bash: |
            echo "##vso[task.setvariable variable=RG]RG0"
            RESOURCEGROUP="aks-ci-$(echo ${RANDOM_NAME} | md5sum | head -c 7)"
            echo "##vso[task.setvariable variable=RESOURCEGROUP]${RESOURCEGROUP}"
        - bash: |
            echo $(registry.url)
            echo $(RG)
            echo $(REGISTRY_URL)
            echo $(RESOURCEGROUP)
          displayName: make ccm
