name: Release kubetest2-aks

on:
  workflow_dispatch:
  push:
    tags:
      - "kubetest2-aks-v*.*.*"

permissions:
  contents: read

jobs:
  build-kubetest2-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Go version
        run: echo "GO_VERSION=$(grep -Eo '^go ([0-9]+\.[0-9]+)$' go.mod | cut -d ' ' -f 2)" >> $GITHUB_ENV
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build binary
        run: |
          cd kubetest2-aks
          make deployer
      - uses: actions/upload-artifact@v3
        with:
          name: kubetest2-aks
          path: kubetest2-aks/bin/kubetest2-aks
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-kubetest2-aks
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-notes.md
          draft: true
          files: |
            ./artifacts/kubetest2-aks/*
